import * as THREE from 'three';
const $=s=>document.querySelector(s), reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const species=[{name:'Eiche',clue:'Rund gelappte Blätter, eine raue Borke und Eicheln.',color:0x527845,bark:0x675039,leaf:'M22 46 C12 43 5 37 11 32 C0 27 7 20 14 22 C5 13 14 8 20 13 C15 2 27 0 29 11 C40 4 47 14 36 20 C48 21 47 31 37 32 C45 40 34 45 26 46 Z'}, {name:'Rotbuche',clue:'Ovale Blätter mit leicht welligem Rand und eine glatte, graue Rinde.',color:0x789448,bark:0x919994,leaf:'M24 46 C-2 32 0 15 24 3 C48 16 51 32 24 46 Z'}, {name:'Ahorn',clue:'Handförmig gelappte Blätter mit spitzen Enden und paarige Flügelfrüchte.',color:0x81a54a,bark:0x756346,leaf:'M24 45 L13 40 L14 33 L3 27 L10 25 L5 14 L17 20 L24 2 L31 20 L43 14 L38 25 L46 27 L34 33 L35 40 Z'}, {name:'Birke',clue:'Dreieckige bis rautenförmige, gezähnte Blätter und weiße Rinde mit dunklen Stellen.',color:0x98b65f,bark:0xe9e5cc,leaf:'M24 45 L14 37 L11 32 L6 28 L8 22 L6 18 L14 13 L24 3 L34 13 L42 18 L40 22 L42 28 L37 32 L34 37 Z'}];
const layers=[['Borke','Die äußere Schutzschicht schützt den Stamm.'],['Bast','Hier werden Zucker und andere Stoffe aus den Blättern transportiert.'],['Kambium','Hier entstehen neue Zellen. Der Stamm wächst in die Dicke.'],['Splintholz','Im äußeren Holz wird Wasser nach oben geleitet.'],['Kernholz','Das ältere, innere Holz. Nicht jede Baumart hat einen farblich abgesetzten Kern.'],['Mark','Das Mark liegt in der Mitte des Stamms.']];
const orders=[{name:'Bretter für die Waldhütte',s:0,wide:true},{name:'Leisten für kleine Modelle',s:1,wide:false},{name:'Bretter für die Ausstellung',s:2,wide:true},{name:'Leisten für Bilderrahmen',s:3,wide:false}];
let round=0,deliveries=0,totalBoards=0,stage='intro',selected=-1,held=false,steer=0,progress=0,cut=0,plan=null,fall=0,sound=false,audio,truckX=0,wrong=0,order,forest=[],saplings=[],boards=[],tree,log,renderer,scene,camera,truck,sawmill,selectionRing,obstacles=[],last=performance.now();
let sequence=[0,1,2], fallbackCanvas;
function tone(freq=500){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.15);}catch{}}
function message(t){$('#toast').textContent=t;}
function mesh(geo,color,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,new THREE.MeshLambertMaterial({color}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,c,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p);}
function makeTree(i,x,z,scale=1){const g=new THREE.Group();scene.add(g);g.position.set(x,0,z);g.scale.setScalar(scale);g.userData.species=i;const s=species[i];mesh(new THREE.CylinderGeometry(.2,.3,2.6,8),s.bark,0,1.3,0,g);if(i===3)for(let j=0;j<5;j++)box(.42,.08,.43,0x494b40,0,.5+j*.38,0,g);for(let j=0;j<4;j++){let m=mesh(new THREE.IcosahedronGeometry(1.1,1),s.color,Math.sin(j*2)*.5,2.7+j*.25,Math.cos(j*2)*.5,g);m.scale.set(1,i===3?1.25:1,1);}g.traverse(o=>o.userData.tree=g);return g;}
function init3D(){try{scene=new THREE.Scene();scene.background=new THREE.Color(0xb8d6bc);scene.fog=new THREE.Fog(0xb8d6bc,30,65);camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(12,13,17);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#world').append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xfff5dc,0x587b57,2.3));const sun=new THREE.DirectionalLight(0xffeccb,2.1);sun.position.set(10,18,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;scene.add(sun);box(28,.5,29,0x719b69,0,-.4,-3);box(4,.03,28,0xb5a17b,0,-.12,-3);for(let i=0;i<4;i++){forest.push(makeTree(i,[-7,-3,3,7][i],[2,-3,-3,2][i]));}for(let i=0;i<15;i++)makeTree(i%4,(i%2?-1:1)*(9+(i%3)*1.8),-10+(i%6)*3,.4+(i%3)*.1);
selectionRing=mesh(new THREE.TorusGeometry(1.5,.055,8,64),0xffcd78,0,.04,0);selectionRing.rotation.x=Math.PI/2;selectionRing.visible=false;
sawmill=new THREE.Group();scene.add(sawmill);sawmill.position.set(0,0,-12);box(6,2.2,3.6,0xdbb87c,0,1.1,0,sawmill);const roof=mesh(new THREE.ConeGeometry(4.3,1.8,4),0x34554b,0,2.9,0,sawmill);roof.rotation.y=Math.PI/4;box(2.4,1.6,.08,0x324b3c,0,.85,1.84,sawmill);for(let i=0;i<3;i++)box(2,.12,.22,0xb9844d,-2,.2+i*.16,2.5,sawmill);
truck=new THREE.Group();scene.add(truck);box(1.3,.45,2.2,0xe9ba64,0,.65,0,truck);box(1.3,.8,.8,0xecbd6c,0,1.05,-.7,truck);box(1.05,.4,.04,0x8fbec3,0,1.2,-1.11,truck);for(let x of [-.72,.72])for(let z of [-.72,.72]){let w=mesh(new THREE.CylinderGeometry(.3,.3,.16,12),0x253930,x,.35,z,truck);w.rotation.z=Math.PI/2;}truck.position.set(0,0,5);truck.visible=false;
log=mesh(new THREE.CylinderGeometry(.43,.43,1.6,16),0x895b36,0,1.1,.25,truck);log.rotation.x=Math.PI/2;
for(let i=0;i<4;i++){let m=mesh(new THREE.CylinderGeometry(.75,.75,.035,24),0x73919a,(i%2?1:-1),0,-1-i*2.2);m.scale.z=.65;obstacles.push(m);m.visible=false;}
new ResizeObserver(resize).observe($('#world'));resize();renderer.domElement.addEventListener('pointerup',e=>{if(stage!=='forest')return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(forest,true)[0];if(hit)select(forest.indexOf(hit.object.userData.tree));});return true;}catch(e){renderer=null;fallbackCanvas=document.createElement('canvas');fallbackCanvas.setAttribute('aria-label','Gezeichnete Waldansicht als Ersatz für 3D');$('#world').append(fallbackCanvas);new ResizeObserver(()=>{fallbackCanvas.width=$('#world').clientWidth*devicePixelRatio;fallbackCanvas.height=$('#world').clientHeight*devicePixelRatio;}).observe($('#world'));fallbackCanvas.addEventListener('pointerup',e=>{if(stage!=='forest')return;const r=fallbackCanvas.getBoundingClientRect();const i=Math.round(((e.clientX-r.left)/r.width-.2)/.2);if(i>=0&&i<4)select(i);});return false;}}
function resize(){if(!renderer)return;const w=$('#world').clientWidth,h=$('#world').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}
function leaf(i){return `<svg viewBox="0 0 50 55" aria-hidden="true"><path d="${species[i].leaf}" fill="#b9d790" stroke="#d5e7bc" stroke-width="1.2"/><path d="M24 50V13" stroke="#55773c" stroke-width="1.5"/></svg>`;}
function header(){order=orders[sequence[round]];$('#round').textContent=`${round+1} / 3`;$('#cargo').textContent=`${deliveries} Lieferungen`;$('#order-title').textContent=order.name;$('#order-hint').textContent=`Gesucht: ${species[order.s].name} · ${order.wide?'breite Bretter':'schmale Leisten'}. ${species[order.s].clue}`;document.querySelectorAll('.step').forEach(e=>e.classList.toggle('active',e.dataset.step===stage));}
function forestUI(){stage='forest';selected=-1;held=false;progress=0;fall=0;header();$('#scene-label').textContent='01 / Baum auswählen';$('#actions').innerHTML=`<p class="font-bold mb-3">Welcher Baum passt zur Bestellung?</p><div class="grid grid-cols-2 gap-2">${species.map((s,i)=>`<button class="tree-card" data-tree="${i}" aria-label="Baum ${i+1} untersuchen">${leaf(i)}<strong>Baum ${i+1}</strong><span class="block text-xs muted mt-1">Blatt ansehen</span></button>`).join('')}</div><p id="tree-info" class="text-sm mt-3 muted">Tippe einen Baum oder eine Blattkarte an.</p><button id="identify" class="ghost text-sm w-full mt-3">Baumnamen entdecken</button><button id="harvest" class="cta w-full mt-3" disabled>Vom Forstteam fällen lassen</button>`;if(renderer){forest.forEach(t=>{t.visible=true;t.rotation.z=0;});truck.visible=false;obstacles.forEach(m=>m.visible=false);boards.forEach(m=>scene.remove(m));boards=[];selectionRing.visible=false;}message('Schau wie beim Waldbesuch auf Blatt und Rinde. Du kannst alles in Ruhe erkunden.');}
function select(i){selected=i;tone(400+i*80);document.querySelectorAll('[data-tree]').forEach(b=>b.classList.toggle('selected',+b.dataset.tree===i));$('#tree-info').textContent=species[i].clue;$('#harvest').disabled=false;if(renderer){selectionRing.position.set(forest[i].position.x,.04,forest[i].position.z);selectionRing.visible=true;}}
function harvest(){if(selected<0)return;if(selected!==order.s){wrong++;message(`Dieser Baum ist eine ${species[selected].name}. Für diese Lieferung suchst du ${species[order.s].name}. Schau noch einmal auf das Blatt.`);tone(220);return;}stage='fall';held=false;fall=0;$('#actions').innerHTML='<p class="text-lg font-bold">Das Forstteam übernimmt.</p><p class="muted mt-3">Der Stamm wird vorbereitet. Gleich geht’s zum Sägewerk.</p>';message('Passender Baum gefunden!');tone(660);}
function driveUI(){stage='drive';header();progress=0;truckX=0;held=false;steer=0;$('#scene-label').textContent='02 / Lieferung zum Sägewerk';$('#actions').innerHTML='<p class="font-bold mb-2">Bring den Stamm zum Sägewerk.</p><p class="text-sm muted mb-4">Halte „Fahren“. Mit links und rechts weichst du den Pfützen aus. Pfützen bremsen nur ein wenig.</p><div class="meter mb-4"><span id="drive-meter"></span></div><button class="cta w-full" data-hold="go">Fahren gedrückt halten ↑</button><div class="grid grid-cols-2 gap-2 mt-3"><button class="ghost" data-hold="left" aria-label="Nach links lenken">← Links</button><button class="ghost" data-hold="right" aria-label="Nach rechts lenken">Rechts →</button></div><button class="ghost w-full mt-3" data-auto="go">Fahrt per Antippen starten / pausieren</button><button id="inspect" class="ghost w-full mt-3">🔍 Baumscheibe ansehen</button><p class="text-xs muted mt-3">Tastatur: ↑ oder Leertaste fährt · ← → lenken</p>';if(renderer){forest[selected].visible=false;selectionRing.visible=false;truck.visible=true;truck.position.set(0,0,5);obstacles.forEach(m=>m.visible=true);}message('Der Baum ist gefällt und entastet. Jetzt folgt der Transport.');}
function plans(wide){const r=1.6,kerf=.05,thickness=wide?.46:.25,minWidth=wide?2.35:1.6;let results=[];let offset=-r+thickness/2;for(let y=offset;y<r;y+=thickness+kerf){const outer=Math.max(Math.abs(y-thickness/2),Math.abs(y+thickness/2));if(outer>=r)continue;const width=2*Math.sqrt(r*r-outer*outer);if(width>=minWidth)results.push({y,width,thickness});}const area=results.reduce((a,b)=>a+b.width*b.thickness,0);return{results,yield:Math.round(area/(Math.PI*r*r)*100),wide};}
function drawMill(){if(!renderer)return;boards.forEach(m=>scene.remove(m));boards=[];forest.forEach(t=>t.visible=false);truck.visible=false;obstacles.forEach(m=>m.visible=false);for(const b of plan.results){let m=box(b.width,b.thickness,3.4,0xe5b97d,0,b.y+1.7,-2);boards.push(m);}const bark=mesh(new THREE.CylinderGeometry(1.64,1.64,3.45,32,1,true),0x78523a,0,1.7,-2);bark.rotation.x=Math.PI/2;boards.push(bark);}
function millUI(){stage='mill';held=false;plan=null;cut=0;header();$('#scene-label').textContent='03 / Dein kleiner Schnittplan';const a=plans(true),b=plans(false);$('#actions').innerHTML=`<p class="font-bold mb-2">Wie schneidest du den Stamm?</p><p class="text-sm muted mb-3">Die Bestellung braucht ${order.wide?'breite Bretter':'schmale Leisten'}. Probiere beide Pläne aus.</p><div class="grid grid-cols-2 gap-2"><button class="tree-card" data-plan="wide"><strong>Breite Bretter</strong><span class="block text-xs muted mt-2">${a.results.length} Bretter · ${a.yield}% Ausbeute</span></button><button class="tree-card" data-plan="thin"><strong>Schmale Leisten</strong><span class="block text-xs muted mt-2">${b.results.length} Leisten · ${b.yield}% Ausbeute</span></button></div><p id="plan-info" class="text-sm muted my-3">Wähle einen Plan. Die 3D-Ansicht zeigt deine Holzstücke.</p><div class="meter my-3"><span id="cut-meter"></span></div><button class="cta w-full" data-hold="saw" disabled>Sägen gedrückt halten</button><button class="ghost w-full mt-3" data-auto="saw" disabled>Sägen per Antippen starten / pausieren</button><button id="inspect" class="ghost w-full mt-3">🔍 Baumscheibe ansehen</button><p class="text-xs muted mt-3">Vereinfachtes Modell: Sägespalte und runde Randstücke bleiben als Verschnitt. Die Stückzahl allein sagt wenig über die Ausbeute.</p>`;if(renderer){truck.position.z=-8;obstacles.forEach(m=>m.visible=false);}message('Sägewerk erreicht. Nun wird aus dem runden Stamm Schnittholz.');}
function choosePlan(wide){held=false;cut=0;plan=plans(wide);drawMill();document.querySelectorAll('[data-plan]').forEach(b=>b.classList.toggle('selected',(b.dataset.plan==='wide')===wide));$('#cut-meter').style.width='0%';const good=wide===order.wide;$('[data-hold="saw"]').disabled=!good;$('[data-auto="saw"]').disabled=!good;$('#plan-info').textContent=good?`Passt zur Bestellung! ${plan.results.length} Holzstücke werden genutzt; ${100-plan.yield}% bleiben als Verschnitt.`:'Dieser Plan wäre für eine andere Bestellung geeignet. Wähle hier die gewünschten Brettmaße.';tone(good?550:300);}
function finishOrder(){stage='delivery';held=false;deliveries++;totalBoards+=plan.results.length;$('#cargo').textContent=`${deliveries} Lieferungen`;$('#actions').innerHTML=`<p class="text-2xl font-black mb-3">Lieferung geschafft! ✨</p><p class="muted mb-4">${plan.results.length} passende ${order.wide?'Bretter':'Leisten'} sind unterwegs. Die Späne können weiter genutzt werden, zum Beispiel für Holzwerkstoffe.</p><button id="next" class="cta w-full">${round===2?'Feierabend ansehen':'Nächste Bestellung →'}</button>`;message('Ein neuer Setzling wächst im Spielwald.');tone(880);if(renderer){const t=forest[selected];saplings.push(makeTree(order.s,t.position.x,t.position.z,.24));boards.forEach((m,i)=>{if(i<plan.results.length)m.position.x+=3;else m.visible=false;});}}
function next(){if(round<2){round++;forestUI();}else{stage='end';$('#summary').textContent=`Du hast ${totalBoards} Holzstücke aus drei Stämmen geliefert. Baumwahl → Fällen → Transport → Sägewerk → Einschnitt → Schnittholz: Deine Produktionskette ist komplett.`;$('#end').showModal();}}
function drawRings(active=-1){const c=$('#ringcanvas'),ctx=c.getContext('2d'),colors=['#755037','#ce9863','#b6cb83','#e7c494','#be915a','#876040'],radii=[210,195,187,178,108,12];ctx.clearRect(0,0,440,440);for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(220,220,radii[i],0,Math.PI*2);ctx.fillStyle=colors[i];ctx.fill();if(i===active){ctx.strokeStyle='#fff6bf';ctx.lineWidth=7;ctx.stroke();}}for(let r of [27,45,58,77,97,119,133,156,176]){ctx.beginPath();ctx.arc(220,220,r,0,Math.PI*2);ctx.strokeStyle='#89643f';ctx.lineWidth=2;ctx.stroke();}if(active===2){ctx.beginPath();ctx.arc(220,220,183,0,Math.PI*2);ctx.strokeStyle='#fcf79e';ctx.lineWidth=7;ctx.stroke();}}
function explore(){held=false;steer=0;$('#layers').innerHTML=layers.map((l,i)=>`<button class="layer" data-layer="${i}">${l[0]}</button>`).join('');$('#layer-info').textContent='Von außen nach innen: Borke → Bast → Kambium → Splintholz → Kernholz → Mark. Die dünnen Schichten sind vergrößert.';$('#ring-info').textContent='';drawRings();$('#explore').showModal();}
function restart(){held=false;steer=0;round=deliveries=totalBoards=wrong=0;sequence=orders.map((_,i)=>i).sort(()=>Math.random()-.5).slice(0,3);if(renderer){saplings.forEach(t=>scene.remove(t));saplings=[];}forestUI();}
$('#intro').addEventListener('cancel',e=>{if(stage==='intro')e.preventDefault();});$('#start').onclick=()=>{const first=stage==='intro';$('#intro').close();if(first)restart();};$('#help').onclick=()=>{held=false;steer=0;$('#intro').showModal();$('#start').textContent=stage==='intro'?'Ab in den Wald →':'Weiter spielen →';};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Ton an':'Ton aus';$('#sound').setAttribute('aria-pressed',sound);$('#sound').setAttribute('aria-label',sound?'Ton ausschalten':'Ton einschalten');tone();};$('#close-explore').onclick=()=>$('#explore').close();$('#again').onclick=()=>{$('#end').close();restart();};$('#rings').onclick=()=>{$('#ring-info').textContent='Dieses Modell zeigt 9 Jahresringe: ungefähr 9 Jahre an dieser Schnittstelle. Breite Ringe zeigen mehr Dickenwachstum. Wasser, Licht oder Temperatur könnten das beeinflusst haben. Die genaue Ursache erkennst du am Ring allein nicht.';};
$('#actions').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.auto&&!b.disabled)held=!held;if(b.dataset.tree!==undefined)select(+b.dataset.tree);if(b.id==='identify'){document.querySelectorAll('[data-tree]').forEach((b,i)=>b.querySelector('strong').textContent=species[i].name);message('Mit Blatt und Rinde lässt sich die Baumart bestimmen.');}if(b.id==='harvest')harvest();if(b.id==='inspect')explore();if(b.dataset.plan)choosePlan(b.dataset.plan==='wide');if(b.id==='next')next();});
$('#layers').addEventListener('click',e=>{const b=e.target.closest('[data-layer]');if(!b)return;const i=+b.dataset.layer;drawRings(i);$('#layer-info').textContent=layers[i][1];document.querySelectorAll('[data-layer]').forEach(el=>el.classList.toggle('active',el===b));});
function holding(b,on){if(b.disabled)return;const k=b.dataset.hold;if(k==='go'&&stage==='drive'||k==='saw'&&stage==='mill')held=on;if(k==='left')steer=on?-1:0;if(k==='right')steer=on?1:0;b.classList.toggle('held',on);}
$('#actions').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-hold]');if(!b||b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);holding(b,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#actions').addEventListener(event,e=>{const b=e.target.closest('[data-hold]');if(b)holding(b,false);});
const keys=new Set();function keyInput(){if(stage==='drive'){held=keys.has('ArrowUp')||keys.has(' ');steer=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);}if(stage==='mill')held=keys.has(' ')&&!!plan&&plan.wide===order.wide;}
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||!['ArrowUp','ArrowLeft','ArrowRight',' '].includes(e.key))return;if(e.key===' '&&e.target.closest('button,a')&&!e.target.closest('[data-hold]'))return;e.preventDefault();keys.add(e.key);keyInput();});addEventListener('keyup',e=>{keys.delete(e.key);keyInput();});function release(){held=false;steer=0;keys.clear();}addEventListener('blur',release);document.addEventListener('visibilitychange',release);document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',release));
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;const paused=!!document.querySelector('dialog[open]');if(!paused){if(stage==='fall'){fall+=dt;if(renderer){forest[selected].rotation.z=reduce?0:-Math.min(fall/1.3,1)*Math.PI/2;}if(fall>1.7)driveUI();}if(stage==='drive'&&held){truckX=THREE.MathUtils.clamp(truckX+steer*dt*2.6,-1.3,1.3);const z=5-progress*13;let wet=obstacles.some((m,i)=>Math.abs(z-(-1-i*2.2))<.8&&Math.abs(truckX-(i%2?1:-1))<.75);progress=Math.min(1,progress+dt*(wet?.027:.052));$('#drive-meter').style.width=progress*100+'%';if(renderer){truck.position.set(truckX,wet&&!reduce?Math.sin(now/60)*.035:0,5-progress*13);truck.rotation.z=reduce?0:-steer*.05;}if(progress>=1)millUI();}if(stage==='mill'&&held&&plan&&plan.wide===order.wide){cut=Math.min(1,cut+dt*.18);$('#cut-meter').style.width=cut*100+'%';if(renderer&&!reduce)boards.forEach((m,i)=>{if(i<plan.results.length)m.position.x=Math.sin(now/30)*.025;});if(cut>=1)finishOrder();}}
if(fallbackCanvas)drawFallback(now);if(renderer){const target=stage==='mill'||stage==='delivery'?new THREE.Vector3(8,8,10):new THREE.Vector3(12,13,17);camera.position.lerp(target,reduce?1:.05);camera.lookAt(0,stage==='mill'||stage==='delivery'?1:0,stage==='mill'||stage==='delivery'?-2:-1);renderer.render(scene,camera);}}

function drawFallback(now){
 const c=fallbackCanvas,ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#b8d6bc';ctx.fillRect(0,0,w,h);ctx.fillStyle='#7b9e6d';ctx.beginPath();ctx.moveTo(0,h*.45);ctx.quadraticCurveTo(w*.35,h*.15,w,h*.5);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();
 ctx.fillStyle='#c6b088';ctx.beginPath();ctx.moveTo(w*.46,h*.42);ctx.lineTo(w*.54,h*.42);ctx.lineTo(w*.8,h);ctx.lineTo(w*.2,h);ctx.fill();
 const hut=(x,y)=>{ctx.fillStyle='#d9b77b';ctx.fillRect(x-w*.09,y-h*.11,w*.18,h*.13);ctx.fillStyle='#34554b';ctx.beginPath();ctx.moveTo(x-w*.12,y-h*.11);ctx.lineTo(x,y-h*.2);ctx.lineTo(x+w*.12,y-h*.11);ctx.fill();ctx.fillStyle='#234c3c';ctx.fillRect(x-w*.025,y-h*.065,w*.05,h*.085);};hut(w*.5,h*.4);
 const paintTree=(i,x,y,scale)=>{const z=w*.06*scale;ctx.fillStyle=['#675039','#919994','#756346','#e9e5cc'][i];ctx.fillRect(x-z*.12,y-z*.6,z*.24,z*1.1);if(i===3){ctx.fillStyle='#4a5442';for(let j=0;j<3;j++)ctx.fillRect(x-z*.12,y-z*.35+j*z*.22,z*.2,z*.06);}ctx.fillStyle=['#527845','#789448','#81a54a','#98b65f'][i];for(let j=0;j<3;j++){ctx.beginPath();ctx.ellipse(x+Math.sin(j*3)*z*.25,y-z*(.9+j*.3),z*.7,z*(i===3?.9:.7),0,0,Math.PI*2);ctx.fill();}};
 for(let i=0;i<8;i++)paintTree(i%4,w*(i%2?.9:.08),h*(.43+(i%4)*.11),.7);
 if(['forest','intro','fall'].includes(stage)){for(let i=0;i<4;i++){const x=w*(.2+i*.2),y=h*(i===1||i===2?.6:.77);if(selected===i){ctx.strokeStyle='#ffd083';ctx.lineWidth=4*devicePixelRatio;ctx.beginPath();ctx.ellipse(x,y+w*.02,w*.07,w*.025,0,0,Math.PI*2);ctx.stroke();}ctx.save();ctx.translate(x,y);if(stage==='fall'&&selected===i&&!reduce)ctx.rotate(-Math.min(fall/1.3,1)*Math.PI/2);paintTree(i,0,0,1.4);ctx.restore();ctx.fillStyle='#193a2c';ctx.font=`bold ${Math.max(13,w*.018)}px system-ui`;ctx.textAlign='center';ctx.fillText('Baum '+(i+1),x,y+w*.06);}}
 if(stage==='drive'){for(let i=0;i<4;i++){ctx.fillStyle='#73919a';ctx.beginPath();ctx.ellipse(w*(i%2?.55:.45),h*(.52+i*.085),w*.03,h*.009,0,0,Math.PI*2);ctx.fill();}const y=h*(.86-progress*.37),x=w*(.5+truckX*.09),s=w*.08;ctx.fillStyle='#253930';ctx.fillRect(x-s*.6,y,s*.2,s*.35);ctx.fillRect(x+s*.4,y,s*.2,s*.35);ctx.fillStyle='#e9ba64';ctx.fillRect(x-s*.6,y-s*.9,s*1.2,s*1.15);ctx.fillStyle='#8fbec3';ctx.fillRect(x-s*.45,y-s*.75,s*.9,s*.25);ctx.fillStyle='#895b36';ctx.fillRect(x-s*.4,y-s*.22,s*.8,s*.65);}
 if(stage==='mill'||stage==='delivery'){ctx.fillStyle='#e7c494';ctx.beginPath();ctx.arc(w*.5,h*.65,Math.min(w,h)*.22,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#78523a';ctx.lineWidth=12*devicePixelRatio;ctx.stroke();if(plan){const r=Math.min(w,h)*.22;for(const b of plan.results){ctx.fillStyle='#dcae70';ctx.strokeStyle='#89643f';ctx.lineWidth=2*devicePixelRatio;const x=w*.5-b.width/3.2*r,y=h*.65+b.y/1.6*r;ctx.fillRect(x,y,b.width/1.6*r,b.thickness/1.6*r);ctx.strokeRect(x,y,b.width/1.6*r,b.thickness/1.6*r);}if(held&&!reduce){ctx.strokeStyle='#fff1c3';ctx.beginPath();ctx.moveTo(w*.3,h*.5+Math.sin(now/200)*h*.05);ctx.lineTo(w*.7,h*.5+Math.sin(now/200)*h*.05);ctx.stroke();}}}
 ctx.textAlign='center';ctx.fillStyle='#234635';ctx.font=`${Math.max(12,w*.015)}px system-ui`;ctx.fillText('Waldansicht · 2D-Modus auf diesem Gerät',w*.5,h*.96);
}

init3D();order=orders[0];header();$('#intro').showModal();requestAnimationFrame(animate);
