'use strict';
(()=>{
const D=window.HOLZ_CHECK_DATA, KEY='holz_zwischencheck_v1', app=document.getElementById('app');
const fresh=()=>({mode:'intro',index:0,answers:{},drafts:{},hints:{},practice:{},retests:{},retry:false});
let s=fresh();
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&['intro','question','results','retest'].includes(saved.mode)&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<12&&['answers','drafts','hints','practice','retests'].every(k=>saved[k]&&typeof saved[k]==='object'))s=saved;}catch{document.getElementById('storage').hidden=false;}
if(s.mode==='retest'&&(!Number.isInteger(s.group)||s.group<0||s.group>3))s.mode='results';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s));}catch{document.getElementById('storage').hidden=false;}};
const qNow=()=>s.mode==='retest'?D.retests[s.group]:D.questions[s.index];
const record=q=>q.id.startsWith('t')?s.retests[q.id]:s.answers[q.id];
const independent=a=>a&&a.first.ok&&!a.first.help;
function evaluate(q,values,unknown=false){const marks=q.order?[!unknown&&values.join('|')===q.correctOrder.join('|')]:q.fields.map((f,i)=>!unknown&&Number(values[i])===f.correct);return {values:[...values],marks,ok:marks.every(Boolean),help:!!s.hints[q.id],unknown};}
function status(a){if(!a)return 'Noch offen';if(independent(a))return 'Selbstständig gelungen';if(a.first.ok)return 'Mit Tipp gelungen';if(a.corrected?.ok)return 'Nach Feedback verbessert';return a.first.unknown?'Noch unsicher':'Weiter üben';}
function controls(q,locked){let draft=s.drafts[q.id]||(q.order?[...q.order]:q.fields.map(()=>''));s.drafts[q.id]=draft;
if(q.order)return `<p>Bringe die Stationen mit den Pfeilen in die richtige Reihenfolge.</p><ol class="order">${draft.map((v,i)=>`<li><span>${esc(v)}</span><button type="button" data-up="${i}" aria-label="${esc(v)} nach oben" ${locked||i===0?'disabled':''}>↑</button><button type="button" data-down="${i}" aria-label="${esc(v)} nach unten" ${locked||i===draft.length-1?'disabled':''}>↓</button></li>`).join('')}</ol>`;
return `<div class="fields">${q.fields.map((f,i)=>`<label class="field">${esc(f.label)}<select data-field="${i}" ${locked?'disabled':''}><option value="">Bitte auswählen</option>${f.options.map((o,j)=>`<option value="${j}" ${String(draft[i])===String(j)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`).join('')}</div>`;}
function feedback(q,a){const attempt=a.corrected||a.first;return `<div class="feedback ${attempt.ok?'good':''}" role="status"><h3>${attempt.ok?'✓ Das passt.':'Schau noch einmal genau hin.'}</h3>${q.fields?`<ul>${q.fields.map((f,i)=>`<li>${attempt.marks[i]?'✓':'→'} ${esc(f.label)} <b>${esc(f.options[f.correct])}</b></li>`).join('')}</ul>`:`<p>${q.correctOrder.map(esc).join(' → ')}</p>`}<p>${esc(q.explain)}</p>${attempt.ok?'':`<p>${esc(q.mis)}</p>`}<p class="subtle">Erster Versuch: ${esc(status({first:a.first}))}. Verbesserungen ändern diesen Stand nicht.</p></div>`;}
function recommendations(){return D.groups.map((g,i)=>({i,need:D.questions.filter(q=>q.group===i).reduce((n,q)=>n+(independent(s.answers[q.id])?0:3-q.level),0)})).filter(g=>g.need>0).sort((a,b)=>b.need-a.need||a.i-b.i).slice(0,2);}
function results(){const rec=recommendations();let reasonTotal=0,reasonGood=0;D.questions.forEach(q=>q.fields?.forEach((f,i)=>{if(f.reason){reasonTotal++;const a=s.answers[q.id];if(a&&!a.first.help&&a.first.marks[i])reasonGood++;}}));
return `<div class="card"><h2>Dein Zwischenstand</h2><p>Keine Note: Die Übersicht zeigt, was dir bei diesen Aufgaben gelungen ist. Eine Aufgabe pro Stufe reicht noch nicht, um eine Kompetenz sicher festzustellen.</p><div class="scroll"><table><thead><tr><th>Bereich</th>${D.levels.map(l=>`<th>${esc(l)}</th>`).join('')}</tr></thead><tbody>${D.groups.map((g,i)=>`<tr><th>${g.id} · ${esc(g.name)}</th>${D.questions.filter(q=>q.group===i).map(q=>`<td>${esc(status(s.answers[q.id]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><h3>Mit Material begründen</h3><p>${reasonGood} von ${reasonTotal} Begründungsteilen im ersten Versuch ohne Tipp passend zugeordnet. Das prüft das Erkennen einer passenden Begründung – noch nicht das eigene Formulieren.</p><p>📁 <b>U.1:</b> Wähle eine Aufgabe. Schreibe zwei eigene Sätze: „Ich sehe im Material …“ und „Daraus schließe ich …, weil …“. Prüfe mit einem Partner, ob dein Beleg wirklich zur Erklärung passt.</p><details><summary>Deine Antworten ansehen</summary>${D.questions.map(q=>`<h3>${esc(q.title)}</h3>${s.answers[q.id]?feedback(q,s.answers[q.id]):'<p>Noch offen.</p>'}`).join('')}</details></div><h2>Dein nächster Schritt</h2>${rec.length?rec.map(({i})=>{const g=D.groups[i],a=s.retests[D.retests[i].id];return `<div class="paper"><h3>📁 Üben: ${g.id} · ${esc(g.name)}</h3><p>${esc(g.exercise)}</p><p>Schreibe deine Ergänzung auf U.1 und notiere die Aufgaben-ID.</p><details><summary>💡 Digital nachschlagen</summary><p><a href="${g.url}" target="_blank" rel="noopener">Material öffnen (neuer Tab)</a> · Kehre danach hierher zurück.</p></details>${a?`<p>Neue Aufgabe: <b>${esc(status(a))}</b>. Dein erster Check bleibt unverändert.</p>`:''}<div class="tools">${s.practice[i]?`<button class="primary" data-test="${i}">${a?'Neue Aufgabe noch einmal ansehen':'Mit einer neuen Aufgabe prüfen'}</button>`:`<button data-practice="${i}">Papierübung erledigt</button>`}</div></div>`;}).join(''):'<div class="paper"><p>Alle Aufgaben sind im ersten Versuch ohne Tipp gelungen. Vertiefe auf U.1: Erfinde einen neuen Brettauftrag. Erkläre, warum eine hohe Ausbeute allein nicht für die Auswahl genügt.</p></div>'}<div class="tools"><a class="button primary" href="lernweg.html?auftrag=A5">Weiter zu A5</a><a class="button" href="materialien/kompetenzraster-woche-1-2.md">Kompetenzraster</a><button data-action="print">Übersicht drucken</button><button data-action="reset">Check neu starten</button></div>`;}
function render(focus=true){save();document.getElementById('progress-area').hidden=s.mode!=='question';document.getElementById('progress').value=s.index+1;document.getElementById('progress-text').textContent=`Aufgabe ${s.index+1} von 12`;
if(s.mode==='intro')app.innerHTML=`<div class="card"><h2>Was kannst du schon anwenden?</h2><p>Du bearbeitest zwölf kurze Aufgaben zu A1–A4. Plane etwa 25–30 Minuten ein.</p><p>📱 Lies die Materialien. Ordne zu, vergleiche und begründe deine Auswahl. Du musst nichts auswendig aufsagen.</p><p>💡 Tipps sind freiwillig. „Ich weiß es noch nicht“ ist erlaubt. Nach jeder Aufgabe bekommst du Feedback. Dein erster Versuch und spätere Verbesserungen bleiben getrennt.</p><p>📁 Am Ende bekommst du höchstens zwei passende Papierübungen. Danach kannst du mit anderem Material prüfen, ob du weitergekommen bist.</p><p class="subtle">Ohne Note und ohne Namen. Der Stand bleibt nur in diesem Browser. Auf gemeinsam genutzten Geräten starte den Check neu.</p><button class="primary" data-action="start">Check starten</button></div>`;
else if(s.mode==='results')app.innerHTML=results();
else{const q=qNow(),a=record(q),locked=!!a&&!s.retry;app.innerHTML=`<p class="kicker">${s.mode==='retest'?'Neue Aufgabe':`${D.groups[q.group].id} · ${D.levels[q.level]}`}</p><div class="layout"><section class="material" aria-label="Material">${q.material}</section><section class="work"><h2>${esc(q.title)}</h2><form id="answer">${controls(q,locked)}<p id="error" class="error" role="alert"></p>${locked?'':`<div class="tools"><button class="primary" type="submit">Antwort prüfen</button><button type="button" data-action="hint">💡 Ich brauche einen Tipp</button><button type="button" data-action="unknown">Ich weiß es noch nicht</button></div>`}</form>${s.hints[q.id]?`<div class="hint">💡 ${esc(q.hint)}</div>`:''}${locked?feedback(q,a):''}${locked?`<div class="tools"><button class="primary" data-action="next">${s.mode==='retest'?'Zur Übersicht':s.index===11?'Zum Zwischenstand':'Nächste Aufgabe'}</button>${(a.corrected||a.first).ok?'':'<button data-action="retry">Antwort verbessern</button>'}</div>`:''}</section></div>`;}
if(focus)app.focus();}
function submit(unknown=false){const q=qNow();const values=s.drafts[q.id];if(!unknown&&!q.order&&values.some(v=>v==='')){document.getElementById('error').textContent='Wähle zu jedem Satz eine Antwort oder „Ich weiß es noch nicht“.';return;}const a=evaluate(q,values,unknown),bag=s.mode==='retest'?s.retests:s.answers;if(!bag[q.id])bag[q.id]={first:a};else if(s.retry)bag[q.id].corrected=a;else return;s.retry=false;render();}
app.addEventListener('submit',e=>{e.preventDefault();submit();});
app.addEventListener('change',e=>{if(e.target.matches('[data-field]')){s.drafts[qNow().id][Number(e.target.dataset.field)]=e.target.value;save();}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-up')||b.hasAttribute('data-down')){const q=qNow();if(record(q)&&!s.retry)return;const i=Number(b.dataset.up??b.dataset.down),j=i+(b.hasAttribute('data-up')?-1:1),d=s.drafts[q.id];if(j>=0&&j<d.length){[d[i],d[j]]=[d[j],d[i]];render(false);}return;}
if(b.hasAttribute('data-practice')){s.practice[Number(b.dataset.practice)]=true;render();return;}
if(b.hasAttribute('data-test')){s.group=Number(b.dataset.test);if(!s.practice[s.group])return;s.mode='retest';s.retry=false;render();return;}
switch(b.dataset.action){case 'start':s.mode='question';break;case 'hint':s.hints[qNow().id]=true;break;case 'unknown':submit(true);return;case 'retry':s.retry=true;break;case 'next':s.retry=false;if(s.mode==='retest'||s.index===11)s.mode='results';else s.index++;break;case 'reset':if(!confirm('Nur deinen Holz-Check auf diesem Gerät löschen und neu starten?'))return;s=fresh();break;case 'print':window.print();return;default:return;}render();});
render(false);
})();
