'use strict';
window.HOLZ_CHECK_DATA=(()=>{
const stem=`<h3>Ein Blick in den Stamm</h3><svg viewBox="0 0 520 310" role="img" aria-label="Stammquerschnitt mit sechs nummerierten Bereichen von außen nach innen"><circle cx="160" cy="155" r="140" fill="#79543c"/><circle cx="160" cy="155" r="120" fill="#d0a56f"/><circle cx="160" cy="155" r="102" fill="#acc884"/><circle cx="160" cy="155" r="92" fill="#ead5a9"/><circle cx="160" cy="155" r="57" fill="#b78b5d"/><circle cx="160" cy="155" r="13" fill="#f8eddb"/>${[135,110,97,73,35,0].map((r,i)=>`<path d="M${160+r} 155 L345 ${30+i*48} H375" fill="none" stroke="#263c31" stroke-width="2"/><text x="384" y="${36+i*48}">${i+1}</text>`).join('')}</svg><p class="art-note">Vereinfachtes Modell. Die äußeren Schichten sind vergrößert dargestellt.</p><p><b>Wortspeicher:</b> Borke = äußere Schutzschicht; Bast = Transport von Zucker; Kambium = bildet neues Gewebe; Splintholz = Wassertransport; Kernholz = innerer Holzbereich; Mark = Mitte.</p>`;
const rings=`<h3>Eine Modell-Baumscheibe</h3><svg viewBox="0 0 460 280" role="img" aria-label="Sechs Jahresringe. Ring 5 ist besonders schmal. Ring 6 außen wurde zuletzt gebildet."><circle cx="155" cy="140" r="125" fill="#f4ddb2"/>${[125,103,97,74,51,27].map(r=>`<circle cx="155" cy="140" r="${r}" fill="none" stroke="#88603c" stroke-width="3"/>`).join('')}<circle cx="155" cy="140" r="3" fill="#513c2c"/>${[14,39,62,85,100,114].map((r,i)=>`<text x="${151+r}" y="137" font-size="13">${i+1}</text>`).join('')}<text x="300" y="90">1 = innen</text><text x="300" y="125">6 = außen</text></svg><p>Ein Jahresring entspricht im Modell einem Wachstumsjahr. Breitere Ringe zeigen mehr Dickenwachstum. Wasser, Licht, Temperatur und Konkurrenz können das Wachstum beeinflussen.</p><p><b>Aussagen:</b><br>A: Ring 5 ist schmaler als Ring 4.<br>B: Im Jahr von Ring 5 hat es bestimmt nicht geregnet.</p>`;
const chain=`<h3>Vom Baum zum Brett</h3><p>🌳 <b>Baum:</b> Er steht im Wald.<br>🪚 <b>Fällen:</b> Der Baum wird zu Boden gebracht.<br>🚛 <b>Transport:</b> Der Stamm wird zum Sägewerk gebracht.<br>🏭 <b>Sägewerk:</b> Der Stamm kommt an und wird bereitgelegt.<br>⚙️ <b>Einschnitt:</b> Sägen teilen den Stamm längs.<br>▰ <b>Schnittholz:</b> Bretter und Balken liegen als Ergebnis vor.</p><p>Das ist eine vereinfachte Produktionskette. Jeder spätere Schritt benötigt das Ergebnis vorheriger Schritte.</p>`;
function planPicture(label,widths){return `<svg viewBox="0 0 260 180" role="img" aria-label="${label}: schematischer Stammquerschnitt, rechteckige Bretter innen, Randstücke außen"><circle cx="130" cy="90" r="80" fill="#dfc8a0" stroke="#79543c" stroke-width="4"/>${widths.map((w,i)=>`<rect x="${130-w/2}" y="${42+i*24}" width="${w}" height="20" fill="#a8c399" stroke="#315b48"/>`).join('')}<text x="10" y="175">${label}</text></svg>`;}
const plans=`<h3>Zwei Schnittpläne</h3>${planPicture('Plan A',[75,145,145,75])}<p class="art-note">Grün: nutzbare Bretter. Außen bleiben Randstücke. In den Schnittfugen entstehen Späne. Schema, nicht maßstäblich; für den Vergleich gilt die Tabelle.</p><table><caption>Didaktische Beispieldaten</caption><tr><th></th><th>Plan A</th><th>Plan B</th></tr><tr><th>Ausbeute</th><td>78 %</td><td>70 %</td></tr><tr><th>Bretter ≥ 15 cm breit</th><td>2</td><td>4</td></tr></table>${planPicture('Plan B',[110,150,150,110])}<p><b>Auftrag:</b> Vier Bretter, jedes mindestens 15 cm breit, aus einem Stamm. Länge und Dicke passen bei beiden Plänen.</p><p>Ausbeute: Anteil des Stamms, der als nutzbare Bretter bleibt.</p>`;
const groups=[
{id:'A1',name:'Stammaufbau',exercise:'Öffne A1.1. Wähle zwei Stammbereiche. Erkläre zu jedem in einem Satz, welche Aufgabe er hat.',url:'baumscheibe.html?modus=entdecken'},
{id:'A2',name:'Jahresringe',exercise:'Öffne A2.2. Schreibe eine Beobachtung und eine mögliche Erklärung. Beginne die Erklärung mit „Eine mögliche Ursache ist …“.',url:'baumscheibe.html?modus=ringe'},
{id:'A3',name:'Produktionskette',exercise:'Öffne A3.1. Erkläre zwei Übergänge mit „Dieser Schritt ist nötig, weil …“.',url:'produktionskette.html'},
{id:'A4',name:'Schnittplan',exercise:'Öffne A4.2. Vergleiche zwei Pläne. Begründe deine Wahl mit Ausbeute und benötigten Brettmaßen.',url:'schnittplan.html'}];
// Each field has one exact answer; reason fields provide separate evidence for K5.
const field=(label,options,correct,reason=false)=>({label,options,correct,reason});
const questions=[
{id:'s1',group:0,level:0,title:'Ordne die Begriffe zu.',material:stem,fields:[field('Bereich 1',['Mark','Borke','Bast'],1),field('Bereich 3',['Splintholz','Kernholz','Kambium'],2),field('Bereich 6',['Mark','Bast','Borke'],0)],hint:'Beginne außen und in der Mitte. Lies danach die Beschreibung der Wachstumsschicht.',explain:'Bereich 1 ist die Borke, 3 das Kambium und 6 das Mark.',mis:'Vergleiche die Lage der Bereiche mit dem Wortspeicher.'},
{id:'s2',group:0,level:1,title:'Erkläre das Dickenwachstum.',material:stem,fields:[field('Der Stamm wird dicker. Entscheidend ist …',['das Mark.','das Kambium.','die Borke.'],1),field('Das passt, weil diese Schicht …',['die Mitte bildet.','Wasser transportiert.','neues Gewebe bildet.'],2,true)],hint:'Suche im Wortspeicher nach der Tätigkeit, bei der etwas Neues entsteht.',explain:'Das Kambium bildet neues Gewebe und ermöglicht so das Dickenwachstum.',mis:'Lage und Aufgabe einer Schicht sind nicht dasselbe. Suche nach der Wachstumstätigkeit.'},
{id:'s3',group:0,level:2,title:'Leite eine mögliche Folge ab.',material:stem+'<p><b>Zusatzinformation:</b> Das Splintholz transportiert Wasser nach oben. Ein tiefer Schaden unterbricht in einem Teil des Stamms diese Leitungswege.</p>',fields:[field('Welche Folge passt zum Text?',['Dort kann weniger Wasser nach oben gelangen.','Das Mark bildet sofort neue Jahresringe.','Die Borke übernimmt den Wassertransport.'],0),field('Welche Information belegt das?',['Das Mark liegt in der Mitte.','Splintholz transportiert Wasser.','Borke ist eine äußere Schicht.'],1,true)],hint:'Verbinde die beschädigte Struktur mit ihrer Aufgabe.',explain:'Unterbrochene Wasserleitungswege können den Transport nach oben beeinträchtigen. Der Text erlaubt keine Aussage, dass der ganze Baum sofort stirbt.',mis:'Begründe die Folge mit der Funktion des betroffenen Bereichs, nicht mit seiner Lage.'},
{id:'r1',group:1,level:0,title:'Lies die Darstellung.',material:rings,fields:[field('Wie viele Wachstumsjahre zeigt das Modell?',['5','6','7'],1),field('Welcher Ring ist schmaler als sein direkter Vorgänger?',['Ring 2','Ring 4','Ring 5'],2)],hint:'Gezählt werden die Jahresringe, nicht die Mitte. Vergleiche die Abstände zwischen den Ringgrenzen.',explain:'Das Modell zeigt sechs Jahresringe. Ring 5 ist deutlich schmaler als Ring 4.',mis:'Unterscheide Ringfläche, Ringgrenze und Mark. Die Ringbreite ist der Abstand zwischen zwei Grenzen.'},
{id:'r2',group:1,level:1,title:'Trenne Beobachtung und Vermutung.',material:rings,fields:[field('A: „Ring 5 ist schmaler als Ring 4.“',['Beobachtung am Bild','Vermutung über eine Ursache'],0),field('B: „Es hat bestimmt nicht geregnet.“',['Beobachtung am Bild','Nicht belegte Erklärung'],1),field('Was folgt sicher aus Ring 5?',['Der Baum hatte keine Blätter.','Das Dickenwachstum war geringer als im Jahr davor.','Der Baum bekam kein Wasser.'],1,true)],hint:'Was kannst du sehen? Und was müsstest du zusätzlich über das Wetter wissen?',explain:'Die Ringbreite ist sichtbar. Sie zeigt geringeres Dickenwachstum. Die genaue Ursache steht nicht im Bild.',mis:'Ein schmaler Ring zeigt das Wachstum, aber nicht unmittelbar das Wetter.'},
{id:'r3',group:1,level:2,title:'Verbessere die Behauptung.',material:rings,fields:[field('Statt „bestimmt kein Regen“ passt …',['„Wassermangel ist eine mögliche Ursache.“','„Es gab sicher zu viel Licht.“','„Der Baum war bestimmt krank.“'],0),field('Was hilft, diese Vermutung zu prüfen?',['Die heutige Farbe eines Brettes','Die Zahl der Bretter im Sägewerk','Wetterdaten und Standortinformationen aus dem betreffenden Jahr'],2,true)],hint:'Eine sichere Erklärung braucht zusätzliche Informationen aus der Zeit des Wachstums.',explain:'Wassermangel ist möglich, aber nicht bewiesen. Wetter- und Standortinformationen helfen, die Vermutung zu überprüfen.',mis:'Tausche nicht eine unbewiesene Ursache gegen eine andere aus. Suche passende Zusatzinformationen.'},
{id:'p1',group:2,level:0,title:'Bringe die Karten in die passende Reihenfolge.',material:chain,order:['Einschnitt','Transport','Schnittholz','Baum','Sägewerk','Fällen'],correctOrder:['Baum','Fällen','Transport','Sägewerk','Einschnitt','Schnittholz'],hint:'Suche zuerst den Ausgangspunkt und das fertige Ergebnis. Ordne dann die Schritte dazwischen.',explain:'Baum → Fällen → Transport → Sägewerk → Einschnitt → Schnittholz.',mis:'Überlege an jedem Übergang: Liegt das Material schon dort vor, wo es gebraucht wird?'},
{id:'p2',group:2,level:1,title:'Beschreibe den Übergang zum Schnittholz.',material:chain,fields:[field('Beim Einschnitt wird …',['der Stamm längs zerteilt.','der Baum gepflanzt.','das Brett zum Stamm zusammengesetzt.'],0),field('Das ist nötig, damit …',['der Stamm wieder wächst.','Bretter und Balken entstehen.','der Transport in den Wald beginnt.'],1,true)],hint:'Vergleiche Ausgangsmaterial und Ergebnis des Sägens.',explain:'Aus dem Stamm entstehen durch den längs gerichteten Einschnitt Bretter und Balken.',mis:'Beschreibe die Veränderung des Materials. Transport verändert seinen Ort, Einschnitt seine Form.'},
{id:'p3',group:2,level:2,title:'Was passiert bei einer Störung?',material:chain+'<p><b>Situation:</b> Der Transport fällt aus. Im Sägewerk sind alle gelagerten Stämme bereits aufgebraucht.</p>',fields:[field('Was kann dort nicht weitergehen?',['Das Wachsen der Bäume','Das Pflanzen im Wald','Der Einschnitt neuer Stämme'],2),field('Warum?',['Der Einschnitt braucht angelieferte Stämme.','Sägen verhindert das Wachstum im Wald.','Bretter müssen vor dem Fällen entstehen.'],0,true)],hint:'Beachte den Zusatz: Auch die Vorräte sind aufgebraucht.',explain:'Ohne Anlieferung und ohne Vorrat fehlen dem Einschnitt die Stämme. Das Wachsen im Wald wird dadurch nicht gestoppt.',mis:'Prüfe, welche Tätigkeit unmittelbar von dem fehlenden Material abhängt.'},
{id:'c1',group:3,level:0,title:'Lies Plan und Tabelle.',material:plans,fields:[field('Wie viele Bretter mit mindestens 15 cm Breite liefert Plan B?',['2','4','70'],1),field('Was sind die Randstücke außerhalb der grünen Rechtecke im Modell?',['Nutzbare Bretter','Kambium','Verschnitt'],2)],hint:'Die Prozentzahl und die Bretterzahl beantworten verschiedene Fragen.',explain:'Plan B liefert vier ausreichend breite Bretter. Die Randstücke zählen im Modell zum Verschnitt.',mis:'Lies die passende Tabellenzeile. Ausbeute ist ein Anteil, keine Anzahl.'},
{id:'c2',group:3,level:1,title:'Vergleiche die Ausbeute.',material:plans,fields:[field('Welcher Plan hat die höhere Ausbeute?',['Plan A','Plan B'],0),field('Das bedeutet …',['mehr ausreichend breite Bretter in jedem Fall.','einen größeren nutzbaren Anteil am Stamm.','dass beim Sägen keine Späne entstehen.'],1,true)],hint:'Lies die Erklärung von Ausbeute. Ein Anteil und eine Stückzahl sind nicht dasselbe.',explain:'78 % ist mehr als 70 %. Plan A nutzt einen größeren Anteil des Stamms, liefert aber nicht mehr ausreichend breite Bretter.',mis:'Eine höhere Ausbeute garantiert nicht, dass die benötigten Maße und Stückzahlen erfüllt werden.'},
{id:'c3',group:3,level:2,title:'Wähle einen Plan für den Auftrag.',material:plans,fields:[field('Welcher Plan erfüllt den Auftrag mit einem Stamm?',['Plan A','Plan B'],1),field('Welche Begründung passt?',['Plan B hat die größere Ausbeute.','Plan A liefert vier passende Bretter.','Nur Plan B liefert vier ausreichend breite Bretter.'],2,true)],hint:'Markiere gedanklich die benötigte Anzahl und Mindestbreite im Auftrag.',explain:'Plan B erfüllt die verlangten vier Bretter mit mindestens 15 cm Breite – trotz niedrigerer Ausbeute.',mis:'Wähle nicht nur die größere Prozentzahl. Prüfe zuerst, ob der Auftrag erfüllt wird.'}
];
const retests=[
{id:'t1',group:0,title:'Neue Situation: Zuckertransport',material:'<h3>Ein anderer Schaden</h3><p>Der Bast transportiert Zucker von den Blättern in andere Bereiche. Ein Schaden unterbricht einen Teil dieser Wege.</p>',fields:[field('Welche Folge ist möglich?',['Weniger Zucker gelangt über diese Wege weiter.','Das Mark wird zur Borke.','Der Stamm verliert sofort alle Jahresringe.'],0),field('Beleg: Der Bast …',['liegt außen.','transportiert Zucker.','bildet die Mitte.'],1,true)],explain:'Die Folge wird aus der Transportaufgabe des Basts abgeleitet.',mis:'Verbinde die Folge mit der genannten Funktion.',hint:'Welcher Stoff wird hier transportiert?'},
{id:'t2',group:1,title:'Neue Situation: breiter Ring',material:'<h3>Beobachtung</h3><p>Ring 8 ist doppelt so breit wie Ring 7. Breitere Ringe zeigen mehr Dickenwachstum. Wetter- und Standortdaten fehlen.</p>',fields:[field('Was ist belegt?',['Im Jahr 8 regnete es doppelt so viel.','Das Dickenwachstum war im Jahr 8 größer.','Der Baum war im Jahr 8 doppelt so hoch.'],1),field('Die Ursache …',['ist sicher allein der Regen.','ist sicher allein die Temperatur.','ist ohne weitere Daten nicht sicher bestimmbar.'],2,true)],explain:'Die Breite belegt stärkeres Dickenwachstum, nicht dessen genaue Ursache.',mis:'Wachstum und Wachstumsursache sind verschiedene Aussagen.',hint:'Welche Information fehlt ausdrücklich?'},
{id:'t3',group:2,title:'Neue Situation: Säge steht still',material:'<h3>Störung</h3><p>Die Säge für den Einschnitt fällt aus. Stämme werden weiterhin angeliefert. Andere Sägen stehen nicht bereit.</p>',fields:[field('Was ist unmittelbar zu erwarten?',['Es entstehen mehr Bretter.','Es werden keine Bäume mehr wachsen.','Stämme warten auf den Einschnitt.'],2),field('Begründung: Ohne Einschnitt …',['werden Stämme nicht zu Schnittholz zerteilt.','können Lastwagen nicht fahren.','werden Bretter wieder zu Stämmen.'],0,true)],explain:'Anlieferung ist möglich, die Verarbeitung zu Schnittholz aber unterbrochen.',mis:'Unterscheide Anlieferung und Verarbeitung.',hint:'Welcher Schritt fehlt zwischen Stamm und Brett?'},
{id:'t4',group:3,title:'Neuer Auftrag: drei breite Bretter',material:'<h3>Andere Pläne</h3><p>Plan C: 65 % Ausbeute, drei Bretter mit mindestens 20 cm Breite.<br>Plan D: 80 % Ausbeute, zwei Bretter mit mindestens 20 cm Breite.</p><p>Auftrag: drei Bretter, jedes mindestens 20 cm breit, aus einem Stamm. Alle anderen Maße passen.</p>',fields:[field('Welcher Plan passt?',['Plan C','Plan D'],0),field('Warum?',['Plan C hat die höhere Ausbeute.','Nur Plan C erfüllt Stückzahl und Breite.','Plan D bietet drei passende Bretter.'],1,true)],explain:'Plan C erfüllt den Auftrag. Die größere Ausbeute von D reicht als Begründung nicht aus.',mis:'Prüfe die geforderte Stückzahl gemeinsam mit der Mindestbreite.',hint:'Wie viele passende Bretter braucht der Auftrag?'}
];
return {groups,questions,retests,levels:['Mindeststandard','Regelstandard','Expertenstandard']};
})();
