const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const base=require('path').join(__dirname,'..');
function setup(saved){const nodes={},listeners={},memory={};if(saved)memory.holz_zwischencheck_v1=saved;const node=id=>nodes[id]??(nodes[id]={hidden:false,innerHTML:'',textContent:'',focus(){},addEventListener(type,cb){listeners[type]=cb;}});const ctx={window:{print(){}},document:{getElementById:node},localStorage:{getItem:k=>memory[k]??null,setItem:(k,v)=>memory[k]=v},confirm:()=>true};vm.createContext(ctx);for(const file of ['zwischencheck-daten.js','zwischencheck.js'])vm.runInContext(fs.readFileSync(base+'/'+file,'utf8'),ctx);const click=dataset=>listeners.click({target:{closest:()=>({dataset,hasAttribute:k=>Object.hasOwn(dataset,k.replace('data-',''))})}});const state=()=>JSON.parse(memory.holz_zwischencheck_v1);const choose=(i,v)=>listeners.change({target:{matches:()=>true,dataset:{field:i},value:String(v)}});const submit=()=>listeners.submit({preventDefault(){}});return {ctx,nodes,click,state,choose,submit,memory};}
let t=setup();const D=t.ctx.window.HOLZ_CHECK_DATA;assert.equal(D.questions.length,12);assert.equal(D.retests.length,4);for(const q of [...D.questions,...D.retests])for(const f of q.fields||[])assert.ok(f.correct>=0&&f.correct<f.options.length);
t.click({action:'start'});t.submit();assert.match(t.nodes.error.textContent,/Wähle/);assert.equal(Object.keys(t.state().answers).length,0);
for(let i=0;i<12;i++){t.click({action:'unknown'});assert.equal(Object.keys(t.state().answers).length,i+1);t.click({action:'next'});}
assert.equal(t.state().mode,'results');assert.equal((t.nodes.app.innerHTML.match(/data-practice=/g)||[]).length,2);
t.click({practice:'0'});t.click({test:'0'});const q=D.retests[0];q.fields.forEach((f,i)=>t.choose(i,f.correct));t.submit();assert.equal(t.state().retests[q.id].first.ok,true);t.click({action:'next'});assert.equal(t.state().answers.s1.first.unknown,true);
t=setup();t.click({action:'start'});t.click({action:'hint'});D.questions[0].fields.forEach((f,i)=>t.choose(i,f.correct));t.submit();assert.equal(t.state().answers.s1.first.help,true);t=setup(t.memory.holz_zwischencheck_v1);assert.match(t.nodes.app.innerHTML,/Mit Tipp gelungen/);
t.click({action:'next'});t.click({action:'unknown'});t.click({action:'retry'});D.questions[1].fields.forEach((f,i)=>t.choose(i,f.correct));t.submit();assert.equal(t.state().answers.s2.first.ok,false);assert.equal(t.state().answers.s2.corrected.ok,true);
t=setup('{invalid');assert.equal(t.state().mode,'intro');
t=setup();t.click({action:'start'});t.click({action:'unknown'});t.click({action:'next'});t.choose(0,0);t.choose(1,2);t.submit();const partial=t.state();partial.mode='results';t=setup(JSON.stringify(partial));assert.match(t.nodes.app.innerHTML,/0 von 8 Begründungen/);
console.log('PASS: 12 items, keys, required inputs, unknowns, two recommendations, paper gate, retest separation, hints, reload, corrections, invalid storage, reason requires matching factual answer.');
