from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
C=[]
def add(id,title,w,goal,steps,hints,check,extra=None): C.append(dict(id=id,title=title,week=w,goal=goal,steps=[dict(kind=s[0],text=s[1],**({'url':s[2]} if len(s)>2 else {})) for s in steps],hints=hints,check=check,extra=extra))
add('A1','Die Baumscheibe',1,'Ich kann die Teile eines Baumstamms benennen.',[
('erkunden','Betrachte eine echte Baumscheibe. Zeige außen, innen und die Mitte.'),('ipad','Tippe die sechs Bereiche an. Lies, welche Aufgabe jeder Bereich hat.','baumscheibe.html?modus=entdecken'),('mappe','Öffne A1.1. Beschrifte die sechs Bereiche mit den Wörtern aus dem Kasten.'),('ipad','Ordne die sechs Begriffe zur Selbstkontrolle zu.','baumscheibe.html?modus=beschriften'),('mappe','Vergleiche A1.1 mit der App. Verbessere deine Beschriftung.'),('halt','Zeige einem Partner das Kambium. Erkläre: Hier wächst der Stamm in die Dicke.')],['Gehe von außen nach innen.','Borke schützt. Kambium ist die Wachstumsschicht. Mark liegt in der Mitte.','Von außen: Borke → Bast → Kambium → Splintholz → Kernholz → Mark.'],['Alle sechs Begriffe stehen auf A1.1.','Ich kann das Kambium zeigen.'])
add('A2','Jahresringe lesen',1,'Ich kann Jahresringe untersuchen und eine Vermutung begründen.',[
('ipad','Zähle die Jahresringe der Modell-Scheibe. Prüfe deine Zahl und suche den breitesten Ring.','baumscheibe.html?modus=ringe'),('mappe','Öffne A2.1. Notiere die Zahl der Ringe. Gib das ungefähre Alter an dieser Schnittstelle an.'),('lesen','Ein breiter Jahresring zeigt stärkeres Dickenwachstum. Wasser, Licht, Temperatur und Konkurrenz können das Wachstum beeinflussen. Die genaue Ursache siehst du am Ring allein nicht.'),('mappe','Bearbeite A2.2. Beschreibe deinen ausgewählten Ring. Schreibe eine mögliche Ursache und begründe deine Vermutung.')],['Beschreibe zuerst nur, was du siehst.','Ein breiter Ring bedeutet: Der Stamm ist in diesem Jahr stärker in die Dicke gewachsen.','Der Ring ist … Ich vermute … Das könnte das Wachstum beeinflusst haben, weil …'],['Ringzahl und Alter stehen auf A2.1.','Ich trenne Beobachtung und Vermutung auf A2.2.'],dict(text='Warum kannst du bei einem Brett nicht immer das Alter des Baumes bestimmen? Zeichne oder erkläre auf V.1.',kind='Transfer'))
add('A3','Vom Baum zum Brett',2,'Ich kann die Produktionskette ordnen und erklären.',[
('ipad','Ordne die sechs Karten. Prüfe deine Reihenfolge.','produktionskette.html'),('mappe','Öffne A3.1. Schreibe die sechs Produktionsschritte in die richtige Reihenfolge.'),('mappe','Schreibe auf A3.1 zu jedem Schritt einen kurzen Satz. Erkläre, was passiert.'),('halt','Lies einem Partner deine Kette vor. Prüft, ob alle Schritte zusammenpassen.')],['Was passiert zuerst im Wald? Was kann erst danach passieren?','Nutze: Zuerst … Danach … Anschließend … Am Ende …','Baum → Fällen → Transport → Sägewerk → Einschnitt → Schnittholz.'],['Meine Kette hat sechs Schritte in der richtigen Reihenfolge.','Zu jedem Schritt steht ein Satz auf A3.1.'])
add('A4','Der Schnittplan',2,'Ich kann zwei Schnittpläne vergleichen.',[
('ipad','Setze Schnitte. Speichere Plan A. Ändere die Schnitte und speichere Plan B.','schnittplan.html'),('mappe','Öffne A4.1. Notiere für beide Pläne die Zahl nutzbarer Bretter und die Ausbeute in Prozent.'),('lesen','Ausbeute ist der Anteil des Stamms, der im Modell als nutzbare Bretter übrig bleibt. Bei jedem Sägeschnitt entstehen Späne. Runde Randstücke und zu kleine Bretter zählen hier zum Verschnitt.'),('mappe','Bearbeite A4.2. Erkläre den Verschnitt. Vergleiche deine Pläne und begründe, welchen du wählen würdest.'),('halt','Zeige deiner Lehrkraft A4.1 und A4.2. Erkläre deine Entscheidung.')],['Vergleiche die beiden Zahlenpaare.','Mehr Bretter bedeuten nicht automatisch mehr Ausbeute.','Ich wähle Plan …, weil … Die gewünschten Brettmaße sind ebenfalls wichtig.'],['Für zwei Pläne stehen Werte auf A4.1.','Ich habe Verschnitt und Entscheidung auf A4.2 erklärt.'],dict(text='Probiere sehr enge und weite Schnitte. Notiere auf V.1, wie sich Bretterzahl und Ausbeute ändern.',kind='Ausprobieren',url='schnittplan.html'))
add('A5','Das Prüflabor',3,'Ich kann Holzproben vergleichbar untersuchen.',[
('mappe','Öffne A5.1. Trage die Nummern deiner drei gleich großen Proben ein.'),('ipad','Untersuche Farbe und Maserung. Schreibe die Beobachtungen direkt in A5.1.','pruefstation.html?station=aussehen'),('ipad','Wiege die Proben. Notiere die Masse in Gramm in A5.1.','pruefstation.html?station=gewicht'),('ipad','Prüfe die Härte nach der Anleitung. Notiere die Spuren in A5.1.','pruefstation.html?station=haerte'),('ipad','Prüfe die Wasseraufnahme. Notiere deine Beobachtungen nach gleicher Wartezeit in A5.1.','pruefstation.html?station=wasser'),('halt','Bereite mit deiner Lehrkraft den Trockenversuch vor. Öffne A7.1. Kennzeichne eine feuchte Probe. Wiege und miss sie. Notiere Datum und Ausgangswerte.'),('erkunden','Lege die feuchte Probe an den vereinbarten Trocknungsplatz. Räume deine Station auf.')],['Notiere zuerst, was du siehst oder misst.','Aussehen: hell, dunkel, rötlich, deutliche oder feine Maserung.','Masse in g; Härte: keine, leichte oder deutliche Spur; Wasser: Tropfen steht oder zieht ein.'],['A5.1 enthält Beobachtungen zu allen vier Stationen.','Die Ausgangswerte des Trockenversuchs stehen auf A7.1.'])
add('A6','Der Prüfbericht',3,'Ich kann Beobachtung, Eigenschaft und Verwendung unterscheiden.',[
('lesen','Beobachtung: Du beschreibst eine Messung oder Spur. Eigenschaft: Du leitest etwas daraus ab. Beispiel: Eine Münze hinterlässt kaum eine Spur. Die Probe ist in diesem Vergleich eher hart. Das ist für eine beanspruchte Oberfläche nützlich.'),('mappe','Öffne A6.1. Wähle zwei Holzarten aus A5.1. Schreibe zu jeder: Ich beobachte … Also ist das Holz … Gut ist das für …'),('halt','Lies einen Bericht vor. Dein Partner prüft: Belegt der Versuch die Eigenschaft? Eine höhere Masse allein belegt keine größere Härte.')],['Nutze eine konkrete Beobachtung aus deiner Tabelle.','Eine deutliche Ritzspur spricht im Vergleich für weicheres Holz.','Ich beobachte, dass … Also ist diese Probe im Vergleich … Gut ist das für …'],['Ich habe für zwei Holzarten je drei zusammenhängende Sätze.','Jede Eigenschaft passt zur gewählten Beobachtung.'])
add('A7','Der Trockenversuch',4,'Ich kann Trocknen, Quellen und Schwinden erklären.',[
('halt','Hole deine Probe und A7.1. Sind die Ausgangswerte aus Woche 3 vorhanden? Wenn nicht, hole dir ein Vergleichsprotokoll von deiner Lehrkraft.'),('erkunden','Wiege dieselbe Probe. Miss Breite und gegebenenfalls Dicke an den markierten Stellen. Nutze dieselben Geräte.'),('mappe','Trage die neuen Werte und das Datum auf A7.1 ein. Berechne: neuer Wert minus alter Wert.'),('lesen','Holzfeuchte bezeichnet Wasser im Holz. Beim Trocknen gibt Holz Wasser ab. Wenn es gebundenes Wasser aus den Zellwänden verliert, schwindet es: Es wird kleiner. Nimmt es dort Wasser auf, quillt es. Die Maßänderung kann so klein sein, dass du sie kaum messen kannst.'),('mappe','Öffne A7.2. Beschreibe deine Ergebnisse. Erkläre Trocknen, Schwinden und Quellen.'),('halt','Erkläre deiner Lehrkraft oder einem Partner zwei mögliche Probleme, wenn feuchtes Holz zu einem Möbelstück verarbeitet wird.')],['Vergleiche erst die Masse, dann die Maße.','Eine kleinere Masse kann durch Wasserabgabe entstehen.','Beim Trocknen gibt Holz … ab. Wenn es schwindet, wird es … Beim Quellen …'],['Vorher- und Nachherwerte stehen auf A7.1.','Ich habe meine Beobachtung und die Begriffe auf A7.2 erklärt.'],dict(text='Warum muss bei einem Holzfußboden Platz für Bewegung bleiben? Erkläre es auf V.1.',kind='Transfer'))
add('A8','Holzfehler finden',4,'Ich kann Riss, Ast und Verwerfen erkennen.',[
('ipad','Ordne die drei Pflichtbegriffe Riss, Ast und Verwerfen den Bildern zu.','holzfehler.html?modus=zuordnen'),('mappe','Öffne A8.1. Zeichne zu jedem Begriff eine kleine Skizze.'),('mappe','Bearbeite A8.2. Wähle einen Fehler. Erkläre, welches Problem er bei einem Produkt verursachen könnte.')],['Ist das Holz aufgerissen, ist eine Aststelle sichtbar oder ist das Brett verformt?','Ein krummes Brett liegt möglicherweise nicht flach auf.','Das Brett mit … könnte bei … Probleme machen, weil …'],['Die drei Pflichtbegriffe sind auf A8.1 dargestellt.','Ich habe eine mögliche technische Folge auf A8.2 erklärt.'],dict(text='Lerne Schüsseln, Verdrehen und Harzgalle kennen. Wähle einen Begriff und erläutere ihn auf V.1.',kind='Mehr erfahren',url='holzfehler.html?modus=vertiefung'))
add('A9','Der Kundenauftrag',5,'Ich kann eine Holzart passend zum Produkt auswählen.',[
('mappe','Lies deine Kundenkarte. Notiere den Auftrag und die Anforderungen auf A9.1.'),('ipad','Lies passende Holzsteckbriefe. Markiere zwei Holzarten und vergleiche sie.','steckbriefe.html'),('mappe','Bearbeite A9.2. Wähle eine Holzart. Verbinde drei Eigenschaften mit den Anforderungen. Nenne einen Nachteil.'),('mappe','Schreibe auf A9.2 eine begründete Empfehlung. Nutze die Informationen aus den Steckbriefen.')],['Wird das Produkt nass? Muss es leicht, hart oder günstig sein?','Verbinde jede Eigenschaft mit einer Anforderung.','Ich empfehle …, weil … Ein Nachteil ist …'],['Ich nenne drei passende Eigenschaften und einen Nachteil.','Meine Begründung passt zum Kundenauftrag.'],dict(text='Begründe auf V.1, warum du die zweite verglichene Holzart nicht gewählt hast.',kind='Transfer'))
add('A10','Meine Produktkarte',5,'Ich kann meine Empfehlung verständlich darstellen.',[
('mappe','Öffne A10.1. Gestalte Feld 1 mit Produktname und einer Skizze.'),('mappe','Fülle die Felder 2 bis 4 aus: Holzart, passende Eigenschaften mit Begründung und ein Nachteil.'),('halt','Lass einen Partner die vier Felder prüfen. Frage: Verstehst du meine Empfehlung?'),('mappe','Verbessere deine Produktkarte und hefte sie in deine Mappe.')],['Nutze deinen Beratungsbogen A9.','Jede Eigenschaft soll erklären, warum das Holz zum Produkt passt.','Das Holz ist … Das ist für mein Produkt gut, weil …'],['Meine Produktkarte enthält alle vier Bereiche.','Ein Partner hat meine Empfehlung geprüft.'],dict(text='Stelle deine fertige Produktkarte mündlich vor. Mit Erlaubnis der Lehrkraft kannst du ein kurzes Video aufnehmen. Die Papierkarte bleibt in der Mappe.',kind='Präsentieren'))
customers=[
 dict(id='schneidebrett',title='Schneidebrett',text='Du berätst eine Person, die täglich kocht. Das Brett wird oft benutzt, von Hand abgewaschen und danach getrocknet. Es soll eine glatte, belastbare Oberfläche haben.',hint='Denke an Härte, Oberfläche und Feuchtigkeit.'),
 dict(id='gartenbank',title='Gartenbank',text='Eine Bank soll draußen stehen. Sie wird nass und muss mehrere Personen tragen. Sie soll lange halten. Die Kundschaft akzeptiert einen höheren Preis.',hint='Denke an Haltbarkeit, Belastung und Schutz vor dauerhafter Nässe.'),
 dict(id='regal',title='Bücherregal',text='Ein Regal steht in einem trockenen Kinderzimmer. Es soll hell aussehen und wenig kosten. Auf den Böden stehen schwere Bücher.',hint='Denke an Kosten, Aussehen und Belastung. Auch Brettdicke und Stützweite sind wichtig.'),
 dict(id='stiftebox',title='Stiftebox',text='Eine Klasse möchte viele Stifteboxen bauen. Das Holz soll preiswert und leicht zu bearbeiten sein. Die Boxen stehen drinnen und werden kaum nass.',hint='Denke an Bearbeitung, Preis und Oberfläche.'),
 dict(id='dachstuhl',title='Dachstuhl',text='Für ein Haus werden viele lange Balken benötigt. Das Holz liegt geschützt unter dem Dach. Kosten und geringes Eigengewicht sind wichtig. Die Balken müssen geeignetes Bauholz sein.',hint='Denke an Menge, Gewicht und Verfügbarkeit. Maße und Festigkeitsnachweis plant eine Fachperson.'),
 dict(id='spielzeug',title='Spielzeugauto',text='Ein kleines Kind bekommt ein Holzauto. Es soll Stöße aushalten und eine glatte Oberfläche haben. Es wird oft angefasst.',hint='Denke an Widerstandsfähigkeit und Oberfläche. Sichere Form und geeignete Oberflächenbehandlung gehören zusätzlich zur Planung.'),
 dict(id='hocker',title='Hocker für die Küche',text='Ein Hocker wird jeden Tag benutzt und manchmal verschoben. Die Oberfläche soll widerstandsfähig sein. Er steht drinnen. Er darf etwas mehr kosten.',hint='Denke an Härte und Belastung. Stabile Verbindungen sind ebenfalls wichtig.'),
 dict(id='bildrahmen',title='Heller Bilderrahmen',text='Eine Person wünscht sich einen hellen Rahmen mit feiner Maserung. Er hängt in einem trockenen Raum. Die Oberfläche soll glatt sein.',hint='Denke an Farbe, Maserung und Bearbeitung.')]
(root/'kurs-daten.js').write_text('window.HOLZ_KURS = '+json.dumps(dict(tasks=C,customers=customers),ensure_ascii=False,indent=2)+';\n')
